[DEV-5734] calc metrics jira groups
athenianco/api-spec pull request #153
Opened 2023-02-07 09:55 UTC by gaetano-guerriero

2023-02-07 09:57 UTC, gaetano-guerriero commented on openapi.yaml
> +            Not compatible with other jira filters in the request:
Note that this limitation is not expressed by the schema: our typescript generator would explode with not/anyOf or allOf/not combinations. The API will check this condition manually.

2023-02-07 11:35 UTC, gaetano-guerriero commented on openapi.yaml
> +        groups:
@vmarkovtsev suggestion for a better name is well accepted

2023-02-08 13:53 UTC, akbarik approved these changes

2023-02-13 10:59 UTC, vmarkovtsev requested changes
> *[Reviewable](https://reviewable.io/reviews/athenianco/api-spec/153)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gaetano-guerriero and @vmarkovtsev)

___
*[`openapi.yaml` line 8245 at r1](https://reviewable.io/reviews/athenianco/api-spec/153#-NO9PViiONEhCGcHLAwu-r1-8245:-NO9Plq4AYIkbmo0HNev:b-j8rw3h) ([raw file](https://github.com/athenianco/api-spec/blob/43835b56954683e78525349bd84402b7c99ad5bf/openapi.yaml#L8245)):*
<details><summary><i>Previously, gaetano-guerriero wrote…</i></summary><blockquote>

@vmarkovtsev suggestion for a better name is well accepted
</blockquote></details>

We seem to stick to "for" in the other endpoints, so let's use "for".
___
*[`openapi.yaml` line 8248 at r1](https://reviewable.io/reviews/athenianco/api-spec/153#-NO9PViiONEhCGcHLAwu-r1-8248:-NO9Q0oF6zJpRFxNo2bP:b5wtvic) ([raw file](https://github.com/athenianco/api-spec/blob/43835b56954683e78525349bd84402b7c99ad5bf/openapi.yaml#L8248)):*
<details><summary><i>Previously, gaetano-guerriero wrote…</i></summary><blockquote>

Note that this limitation is not expressed by the schema: our typescript generator would explode with not/anyOf or allOf/not combinations. The API will check this condition manually.
</blockquote></details>

We would ideally rewrite this endpoint usage in the frontend to always use `for`/`groups` to stay uniform with the rest.
BTW the reason why the JIRA metrics doesn't allow grouping is just that it required more code and we were in quite a hurry to add JIRA asap.


<!-- Sent from Reviewable.io -->

2023-02-13 11:27 UTC, gaetano-guerriero reviewed
> *[Reviewable](https://reviewable.io/reviews/athenianco/api-spec/153)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @vmarkovtsev)

___
*[`openapi.yaml` line 8248 at r1](https://reviewable.io/reviews/athenianco/api-spec/153#-NO9PViiONEhCGcHLAwu-r1-8248:-NO9Wfy00YjDrgHWATwG:b-qee4kv) ([raw file](https://github.com/athenianco/api-spec/blob/43835b56954683e78525349bd84402b7c99ad5bf/openapi.yaml#L8248)):*
<details><summary><i>Previously, vmarkovtsev (Vadim Markovtsev) wrote…</i></summary><blockquote>

We would ideally rewrite this endpoint usage in the frontend to always use `for`/`groups` to stay uniform with the rest.
BTW the reason why the JIRA metrics doesn't allow grouping is just that it required more code and we were in quite a hurry to add JIRA asap.
</blockquote></details>

We can start migrating the calls to `for`, I guess we  have to keep the rest of parameters to not break compatibility ?


<!-- Sent from Reviewable.io -->

2023-02-13 15:05 UTC, vmarkovtsev approved these changes
> *[Reviewable](https://reviewable.io/reviews/athenianco/api-spec/153)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @vmarkovtsev)

___
*[`openapi.yaml` line 8248 at r1](https://reviewable.io/reviews/athenianco/api-spec/153#-NO9PViiONEhCGcHLAwu-r1-8248:-NOAIgrI1q978zz64xhk:b-pzwto5) ([raw file](https://github.com/athenianco/api-spec/blob/43835b56954683e78525349bd84402b7c99ad5bf/openapi.yaml#L8248)):*
<details><summary><i>Previously, gaetano-guerriero wrote…</i></summary><blockquote>

We can start migrating the calls to `for`, I guess we  have to keep the rest of parameters to not break compatibility ?
</blockquote></details>

Yep, backward-compatible


<!-- Sent from Reviewable.io -->

2023-02-13 15:05 UTC, merged